### ISSUE TITLE
profileUrl incorrectly has a query parameter of id_token

### ISSUE THREAD

**Issue by robbailey3** [davidep87/passport-token-google#4]
According to the readme, any requests to authenticate require a access_token parameter. However, the profileUrl has a parameter of id_token. Passing in an access token does not work. 

CodeRef: 
`GoogleTokenStrategy.prototype.userProfile = function(accessToken, done) {
var profileUrl = 'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token='+accessToken;
this._oauth2.get(profileUrl, null, function (err, body, res) {...`

**Comment by danimateo** [comment]
See this https://github.com/davidep87/passport-token-google/issues/7
