### ISSUE TITLE
Issue with profileUrl

### ISSUE THREAD

**Issue by danimateo** [davidep87/passport-token-google#7]
Hello, i spent some time debugging why this wasn't working and I found out that this line:
`  var profileUrl = 'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token='+accessToken;`
should actually be
`  var profileUrl = 'https://www.googleapis.com/oauth2/v3/tokeninfo?access_token='+accessToken;`

Maybe the google api has changed? Id token does nothing and it fails with an unauthorized code.

Edit: Actually, I confused the id_token with the access_token. The module expects an id_token apparently. You should update the documentation to specify that the id_token should be used or use the [https://www.googleapis.com/oauth2/v3/userinfo?access_token=](https://www.googleapis.com/oauth2/v3/userinfo?access_token=) url.

**Comment by salmanahmad94** [comment]
@danimateo well, conventionally, the ` access_token` param should be used.
